import os
from contextlib import contextmanager
from datetime import datetime

# POSTGRESQL CONFIGURATION
DATABASE_URL = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("POSTGRES_URL")
)

DB_CONNECT_TIMEOUT = int(os.environ.get("DB_CONNECT_TIMEOUT", "10"))

# VALIDATION
def _validate_database_configuration():
    # Validate that PostgreSQL is configured.
    if not DATABASE_URL:
        raise RuntimeError(
            "PostgreSQL DATABASE_URL is not configured. "
            "Set DATABASE_URL in your local environment or "
            "Streamlit Secrets."
        )

# POSTGRESQL DRIVER
def _get_postgres_driver():
    """Return the psycopg v3 PostgreSQL driver."""
    try:
        import psycopg
        return psycopg
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "PostgreSQL driver is not installed. "
            "Add 'psycopg[binary]>=3.2,<4' to requirements.txt."
        ) from exc

# DATABASE CONNECTION
@contextmanager
def _connection():
    """Create a PostgreSQL connection."""
    _validate_database_configuration()
    psycopg = _get_postgres_driver()
    conn = None

    try:
        conn = psycopg.connect(DATABASE_URL,connect_timeout=DB_CONNECT_TIMEOUT,)
        yield conn
    except Exception:
        if conn is not None:
            try:
                conn.rollback()
            except Exception:
                pass
        raise

    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass

# SQL HELPERS
def _prepare_sql(sql):
    return sql


def _primary_key_sql():
    # PostgreSQL primary-key definition.
    return (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY "
        "PRIMARY KEY"
    )

# TABLE INFORMATION
def _table_exists(conn, table_name):
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = %s
        )
        """,
        (table_name,),
    )
    result = cursor.fetchone()
    return bool(result and result[0])

def _table_columns(conn, table_name):
    # Return PostgreSQL table column names.
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = %s
        ORDER BY ordinal_position
        """,
        (table_name,),
    )

    return [row[0]for row in cursor.fetchall()]

# ERROR HELPERS
def _duplicate_error(exc):
    # Detect PostgreSQL duplicate/unique constraint errors.
    message = str(exc).lower()
    return any(
        text in message
        for text in (
            "duplicate key",
            "unique constraint",
            "uniqueviolation",
            "already exists",
        )
    )

# DATABASE INITIALIZATION
def init_database():
    _validate_database_configuration()

    try:
        with _connection() as conn:
            _init_db_tables(conn)
        print("✅ PostgreSQL database initialized successfully.")
        return True

    except Exception as exc:
        print(f"❌ PostgreSQL database initialization failed: {exc}")
        raise RuntimeError(
            f"PostgreSQL database initialization failed: {exc}"
        ) from exc

# CREATE / MIGRATE TABLES
def _init_db_tables(conn):
    # Create PostgreSQL tables, indexes and required migrations.
    cursor = conn.cursor()
    pk_sql = _primary_key_sql()

    # PROJECTS TABLE
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS projects (
            project_id {pk_sql},
            project_name TEXT UNIQUE NOT NULL,
            created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # PRETEST CHANGES TABLE
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS pretest_changes (
            change_id {pk_sql},
            project_id INTEGER NOT NULL,
            run_id TEXT NOT NULL,
            tier TEXT NOT NULL,
            changes TEXT NOT NULL,
            change_date DATE NOT NULL,
            created_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (project_id)
                REFERENCES projects(project_id)
                ON DELETE CASCADE
        )
        """
    )

    conn.commit()

    # MIGRATION
    columns = _table_columns(conn,"pretest_changes",)

    # Add tier if older database does not contain it.
    if "tier" not in columns:
        try:
            cursor.execute(
                """
                ALTER TABLE pretest_changes
                ADD COLUMN tier TEXT DEFAULT ''
                """
            )

            conn.commit()
            print("✅ Added missing 'tier' column.")

        except Exception as exc:
            conn.rollback()
            # Check again because another process may have
            # performed the migration concurrently.
            columns = _table_columns(conn,"pretest_changes",)

            if "tier" not in columns:
                raise RuntimeError(
                    f"Could not add 'tier' column: {exc}"
                ) from exc

    # INDEX: PROJECT + DATE
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS
        idx_pretest_changes_project_date
        ON pretest_changes
        (
            project_id,
            change_date DESC,
            created_timestamp DESC
        )
        """
    )

    # INDEX: PROJECT + RUN ID
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS
        idx_pretest_changes_project_run
        ON pretest_changes
        (
            project_id,
            run_id
        )
        """
    )

    conn.commit()

# PROJECT FUNCTIONS
def get_all_projects():
    # Return all project names sorted alphabetically.
    try:
        with _connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                SELECT project_name
                FROM projects
                ORDER BY project_name
                """
            )
            return [row[0]for row in cursor.fetchall()]

    except Exception as exc:
        print(f"❌ Error retrieving projects: {exc}")
        return []


def create_project(project_name):
    # Create a new project.
    try:
        if not project_name or not project_name.strip():
            print("❌ Project name cannot be empty.")
            return False

        project_name = project_name.strip()
        with _connection() as conn:
            try:
                cursor = conn.cursor()
                cursor.execute(
                    """
                    INSERT INTO projects
                    (project_name)
                    VALUES (%s)
                    """,
                    (project_name,),
                )

                conn.commit()
                return True

            except Exception as exc:
                conn.rollback()
                if _duplicate_error(exc):
                    print(f"❌ Project '{project_name}' already exists.")

                    return False

                print(f"❌ Database error creating project: {exc}")

                return False

    except Exception as exc:
        print(f"❌ Unexpected error in create_project: {exc}")

        return False


def get_project_id(project_name):
    # Get project ID by project name.
    if not project_name:
        return None
    try:
        with _connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                SELECT project_id
                FROM projects
                WHERE project_name = %s
                """,
                (project_name,),
            )
            result = cursor.fetchone()
            return result[0] if result else None

    except Exception as exc:
        print(f"❌ Error getting project ID: {exc}")
        return None

# PRETEST CHANGE FUNCTIONS
def add_pretest_change(
    project_name,
    run_id,
    tier,
    changes,
    change_date,
):
    """
    Add a new pretest change.

    Duplicate Run IDs are allowed.
    The second return value indicates whether the Run ID
    already existed for this project.
    """
    try:
        if not all(
            [project_name,run_id,tier,changes,change_date,]
        ):
            print("❌ All fields are required for pretest change.")
            return False, None

        project_name = str(project_name).strip()
        run_id = str(run_id).strip()
        tier = str(tier).strip()
        changes = str(changes).strip()

        with _connection() as conn:
            cursor = conn.cursor()

            # Find project
            cursor.execute(
                """
                SELECT project_id
                FROM projects
                WHERE project_name = %s
                """,
                (project_name,),
            )

            project = cursor.fetchone()
            if not project:
                print(f"❌ Project '{project_name}' not found.")
                return False, None

            project_id = project[0]

            # Check duplicate Run ID
            cursor.execute(
                """
                SELECT 1
                FROM pretest_changes
                WHERE project_id = %s
                  AND run_id = %s
                LIMIT 1
                """,
                (project_id,run_id,),
            )

            is_duplicate = (cursor.fetchone() is not None)

            # Insert record
            cursor.execute(
                """
                INSERT INTO pretest_changes
                (
                    project_id,
                    run_id,
                    tier,
                    changes,
                    change_date
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (project_id,run_id,tier,changes,change_date,),
            )

            conn.commit()
            return True, is_duplicate

    except Exception as exc:
        print(f"❌ Database error adding pretest change: {exc}")
        return False, None


def update_pretest_change(
    project_name,
    run_id,
    tier,
    changes,
    change_date,
):
    """
    Update an existing pretest change identified by
    project name and Run ID.
    """
    try:
        if not all(
            [project_name,run_id,tier,changes,change_date,]
        ):
            print("❌ All fields are required for updating pretest change.")
            return False

        with _connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                UPDATE pretest_changes
                SET
                    tier = %s,
                    changes = %s,
                    change_date = %s
                WHERE project_id = (
                    SELECT project_id
                    FROM projects
                    WHERE project_name = %s
                )
                AND run_id = %s
                """,
                (tier,changes,change_date,project_name,run_id,),
            )

            updated = cursor.rowcount > 0
            conn.commit()
            return updated

    except Exception as exc:
        print(f"❌ Database error updating pretest change: {exc}")
        return False

# DATE HELPER
def _parse_change_date(date_value):
    # Return a comparable Python date value.
    if date_value is None:
        return datetime.min.date()

    date_str = str(date_value).strip()

    if not date_str:
        return datetime.min.date()

    formats = (
        "%Y-%m-%d",
        "%Y-%m-%d %H:%M:%S",
        "%d-%m-%Y",
        "%d-%m-%Y %H:%M:%S",
    )

    for fmt in formats:
        try:
            return datetime.strptime(date_str,fmt,).date()
        except ValueError:
            continue

    try:
        return datetime.fromisoformat(date_str).date()

    except ValueError:
        return datetime.min.date()

# GET PRETEST CHANGES
def get_pretest_changes(project_name):
    # Get all pretest changes for a project,newest date first.
    return get_pretest_changes_filtered(project_name)

def get_pretest_changes_filtered(
    project_name,
    run_id=None,
    tier=None,
    start_date=None,
    end_date=None,
):
    """
    Get pretest changes filtered by:
    - Project
    - Run ID
    - Tier
    - Start date
    - End date
    """

    try:
        query = """
            SELECT
                run_id,
                tier,
                changes,
                change_date
            FROM pretest_changes
            WHERE project_id = (
                SELECT project_id
                FROM projects
                WHERE project_name = %s
            )
        """

        params = [project_name]

        # Run ID
        if run_id:
            query += """
                AND run_id ILIKE %s
            """
            params.append(f"%{run_id}%")

        # Tier
        if tier:
            query += """
                AND tier ILIKE %s
            """
            params.append(f"%{tier}%")

        # Start date
        if start_date:
            query += """
                AND change_date >= %s
            """
            params.append(start_date)

        # End date
        if end_date:
            query += """
                AND change_date <= %s
            """
            params.append(end_date)

        # PostgreSQL date ordering
        query += """
            ORDER BY
                change_date DESC,
                created_timestamp DESC
        """

        with _connection() as conn:
            cursor = conn.cursor()
            cursor.execute(query,tuple(params),)
            return cursor.fetchall()

    except Exception as exc:
        print(f"❌ Error retrieving pretest changes: {exc}")
        return []

# DATAFRAME
def get_pretest_changes_as_dataframe(project_name):
    # Return pretest changes as a pandas DataFrame.
    import pandas as pd
    changes = get_pretest_changes(
        project_name
    )
    if not changes:
        return pd.DataFrame(
            columns=[
                "Sr. No.",
                "Run ID",
                "Tier",
                "Changes Done",
                "Date",
            ]
        )

    data = []
    for idx, (
        run_id,
        tier,
        changes_text,
        change_date,
    ) in enumerate(changes, 1):
        data.append(
            {
                "Sr. No.": idx,
                "Run ID": run_id,
                "Tier": tier,
                "Changes Done": changes_text,
                "Date": change_date,
            }
        )

    return pd.DataFrame(data)

# DELETE PRETEST CHANGE
def delete_pretest_change(project_name,run_id,):
    # Delete a pretest change by project + Run ID.
    try:
        with _connection() as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                DELETE FROM pretest_changes
                WHERE project_id = (
                    SELECT project_id
                    FROM projects
                    WHERE project_name = %s
                )
                AND run_id = %s
                """,
                (
                    project_name,
                    run_id,
                ),
            )

            deleted = cursor.rowcount > 0
            conn.commit()
            return deleted

    except Exception as exc:
        print(f"❌ Error deleting pretest change: {exc}")
        return False

# DELETE PROJECT
def delete_project(project_name):
    # Delete a project and all associated pretest changes.
    try:
        with _connection() as conn:
            cursor = conn.cursor()
            # Find project
            cursor.execute(
                """
                SELECT project_id
                FROM projects
                WHERE project_name = %s
                """,
                (project_name,),
            )

            project = cursor.fetchone()
            if not project:
                return False

            project_id = project[0]

            # Delete child records explicitly.
            cursor.execute(
                """
                DELETE FROM pretest_changes
                WHERE project_id = %s
                """,
                (project_id,),
            )

            # Delete project
            cursor.execute(
                """
                DELETE FROM projects
                WHERE project_id = %s
                """,
                (project_id,),
            )

            deleted = cursor.rowcount > 0
            conn.commit()
            return deleted

    except Exception as exc:
        print(f"❌ Error deleting project: {exc}")
        return False
