import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime


# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

DB_FILE = os.environ.get("DB_FILE", "pretest_changes.db")

# Support either DATABASE_URL or POSTGRES_URL.
DATABASE_URL = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("POSTGRES_URL")
)

# Optional explicit database type.
# Examples:
#   DB_TYPE=sqlite
#   DB_TYPE=postgres
#   DB_TYPE=postgresql
DB_TYPE = os.environ.get("DB_TYPE", "").strip().lower()


# =============================================================================
# DATABASE TYPE
# =============================================================================

def _is_postgres_enabled():
    """
    Determine whether PostgreSQL should be used.

    PostgreSQL is enabled when:
      - DB_TYPE is postgres/postgresql, OR
      - DATABASE_URL/POSTGRES_URL is configured.

    Otherwise SQLite is used.
    """
    return (
        DB_TYPE in {"postgres", "postgresql"}
        or bool(DATABASE_URL)
    )


def _database_name():
    """Return a friendly database name for error messages."""
    return "PostgreSQL" if _is_postgres_enabled() else "SQLite"


def _prepare_sql(sql):
    """
    Convert SQLite-style '?' placeholders to PostgreSQL '%s' placeholders.

    The application uses '?' throughout its SQL so the same queries can work
    with both database engines.
    """
    if _is_postgres_enabled():
        return sql.replace("?", "%s")

    return sql


def _primary_key_sql():
    """
    Return a database-specific auto-increment primary key definition.
    """
    if _is_postgres_enabled():
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

    return "INTEGER PRIMARY KEY AUTOINCREMENT"


# =============================================================================
# CONNECTION MANAGEMENT
# =============================================================================

@contextmanager
def _connection():
    """
    Open a database connection.

    PostgreSQL:
        Uses psycopg first, then psycopg2.

    SQLite:
        Uses the local DB_FILE.

    Important:
        PostgreSQL connection failures are NOT silently converted to SQLite.
        This prevents deployment configuration errors from being hidden.
    """

    if _is_postgres_enabled():

        if not DATABASE_URL:
            raise RuntimeError(
                "PostgreSQL is enabled but DATABASE_URL is not configured. "
                "Set DATABASE_URL in your Streamlit deployment secrets."
            )

        conn = None

        # ---------------------------------------------------------------------
        # Try psycopg 3
        # ---------------------------------------------------------------------
        try:
            import psycopg

            conn = psycopg.connect(
                DATABASE_URL,
                connect_timeout=10,
            )

        except ModuleNotFoundError:

            # -------------------------------------------------------------
            # Try psycopg2
            # -------------------------------------------------------------
            try:
                import psycopg2

                conn = psycopg2.connect(
                    DATABASE_URL,
                    connect_timeout=10,
                )

            except ModuleNotFoundError as exc:
                raise RuntimeError(
                    "PostgreSQL is configured but no PostgreSQL driver is "
                    "installed. Add 'psycopg[binary]' or 'psycopg2-binary' "
                    "to requirements.txt."
                ) from exc

            except Exception as exc:
                raise RuntimeError(
                    f"PostgreSQL connection failed: {exc}"
                ) from exc

        except Exception as exc:
            raise RuntimeError(
                f"PostgreSQL connection failed: {exc}"
            ) from exc

        try:
            yield conn
        finally:
            try:
                conn.close()
            except Exception:
                pass

        return

    # =========================================================================
    # SQLITE
    # =========================================================================

    conn = sqlite3.connect(
        DB_FILE,
        timeout=10.0,
    )

    try:
        # Enable foreign-key enforcement for SQLite.
        conn.execute("PRAGMA foreign_keys = ON")

        yield conn

    finally:
        try:
            conn.close()
        except Exception:
            pass


# =============================================================================
# DATABASE METADATA HELPERS
# =============================================================================

def _table_columns(conn):
    """
    Return column names for pretest_changes.

    Works with both SQLite and PostgreSQL.
    """

    if _is_postgres_enabled():

        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
            ORDER BY ordinal_position
            """,
            ("pretest_changes",),
        )

        return [row[0] for row in cursor.fetchall()]

    # SQLite
    cursor = conn.cursor()

    cursor.execute(
        "PRAGMA table_info(pretest_changes)"
    )

    return [row[1] for row in cursor.fetchall()]


def _duplicate_error(exc):
    """
    Detect duplicate/unique constraint errors across SQLite and PostgreSQL.
    """

    message = str(exc).lower()

    return (
        "integrity" in message
        or "duplicate key" in message
        or "unique constraint" in message
        or "already exists" in message
        or "uniqueviolation" in message
    )


# =============================================================================
# DATABASE INITIALIZATION
# =============================================================================

def init_database():
    """
    Initialize the database and required tables.

    This function intentionally does NOT silently fall back from PostgreSQL
    to SQLite. If PostgreSQL is configured but unavailable, the real error
    should be shown so deployment configuration can be fixed.
    """

    try:
        with _connection() as conn:
            _init_db_tables(conn)

    except Exception as exc:

        database_name = _database_name()

        raise RuntimeError(
            f"{database_name} database initialization failed: {exc}"
        ) from exc


def _init_db_tables(conn):
    """
    Create database tables and indexes.
    """

    cursor = conn.cursor()

    pk_sql = _primary_key_sql()

    # =========================================================================
    # PROJECTS TABLE
    # =========================================================================

    projects_sql = f"""
        CREATE TABLE IF NOT EXISTS projects (
            project_id {pk_sql},
            project_name TEXT UNIQUE NOT NULL,
            created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """

    cursor.execute(
        _prepare_sql(projects_sql)
    )

    # =========================================================================
    # PRETEST CHANGES TABLE
    # =========================================================================

    pretest_sql = f"""
        CREATE TABLE IF NOT EXISTS pretest_changes (
            change_id {pk_sql},
            project_id INTEGER NOT NULL,
            run_id TEXT NOT NULL,
            tier TEXT NOT NULL,
            changes TEXT NOT NULL,
            change_date DATE NOT NULL,
            created_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (project_id)
                REFERENCES projects(project_id)
                ON DELETE CASCADE
        )
    """

    cursor.execute(
        _prepare_sql(pretest_sql)
    )

    # Commit table creation before checking/altering columns.
    conn.commit()

    # =========================================================================
    # BACKWARD COMPATIBILITY
    # =========================================================================

    columns = _table_columns(conn)

    if "tier" not in columns:

        try:

            if _is_postgres_enabled():

                cursor.execute(
                    """
                    ALTER TABLE pretest_changes
                    ADD COLUMN tier TEXT DEFAULT ''
                    """
                )

            else:

                cursor.execute(
                    """
                    ALTER TABLE pretest_changes
                    ADD COLUMN tier TEXT DEFAULT ''
                    """
                )

            conn.commit()

        except Exception as exc:

            # It is possible another process created the column between
            # checking and altering it. Only ignore the specific situation
            # where the column already exists.
            if "already exists" not in str(exc).lower():
                conn.rollback()
                raise

    # =========================================================================
    # INDEXES
    # =========================================================================

    index_sql = """
        CREATE INDEX IF NOT EXISTS idx_pretest_changes_project_date
        ON pretest_changes (
            project_id,
            change_date DESC,
            created_timestamp DESC
        )
    """

    cursor.execute(
        _prepare_sql(index_sql)
    )

    # Useful index for project + Run ID lookups.
    run_index_sql = """
        CREATE INDEX IF NOT EXISTS idx_pretest_changes_project_run
        ON pretest_changes (
            project_id,
            run_id
        )
    """

    cursor.execute(
        _prepare_sql(run_index_sql)
    )

    conn.commit()


# =============================================================================
# PROJECT FUNCTIONS
# =============================================================================

def get_all_projects():
    """
    Get all project names sorted alphabetically.
    """

    try:

        with _connection() as conn:

            cursor = conn.execute(
                _prepare_sql(
                    """
                    SELECT project_name
                    FROM projects
                    ORDER BY project_name
                    """
                )
            )

            return [
                row[0]
                for row in cursor.fetchall()
            ]

    except Exception as exc:

        print(
            f"❌ Error retrieving projects: {exc}"
        )

        return []


def create_project(project_name):
    """
    Create a new project.

    Returns:
        True  -> project created
        False -> project already exists or creation failed
    """

    try:

        if not project_name or not project_name.strip():

            print(
                "❌ Project name cannot be empty"
            )

            return False

        project_name = project_name.strip()

        with _connection() as conn:

            try:

                conn.execute(
                    _prepare_sql(
                        """
                        INSERT INTO projects (project_name)
                        VALUES (?)
                        """
                    ),
                    (project_name,),
                )

                conn.commit()

                return True

            except Exception as exc:

                conn.rollback()

                if _duplicate_error(exc):

                    print(
                        f"❌ Project '{project_name}' already exists"
                    )

                    return False

                print(
                    f"❌ Database error creating project: {exc}"
                )

                return False

    except Exception as exc:

        print(
            f"❌ Unexpected error in create_project: {exc}"
        )

        return False


def get_project_id(project_name):
    """
    Get project ID by project name.
    """

    if not project_name:
        return None

    try:

        with _connection() as conn:

            result = conn.execute(
                _prepare_sql(
                    """
                    SELECT project_id
                    FROM projects
                    WHERE project_name = ?
                    """
                ),
                (project_name,),
            ).fetchone()

            return result[0] if result else None

    except Exception as exc:

        print(
            f"❌ Error retrieving project ID: {exc}"
        )

        return None


# =============================================================================
# PRETEST CHANGE FUNCTIONS
# =============================================================================

def add_pretest_change(
    project_name,
    run_id,
    tier,
    changes,
    change_date,
):
    """
    Add a new pretest change.

    Duplicate Run IDs are allowed.

    Returns:
        (True, False) -> successfully inserted, not duplicate
        (True, True)  -> successfully inserted, duplicate Run ID detected
        (False, None) -> failed
    """

    try:

        if not all(
            [
                project_name,
                run_id,
                tier,
                changes,
                change_date,
            ]
        ):

            print(
                "❌ All fields are required for pretest change"
            )

            return False, None

        project_name = str(project_name).strip()
        run_id = str(run_id).strip()
        tier = str(tier).strip()
        changes = str(changes).strip()
        change_date = str(change_date).strip()

        with _connection() as conn:

            try:

                # -------------------------------------------------------------
                # Find project
                # -------------------------------------------------------------

                project = conn.execute(
                    _prepare_sql(
                        """
                        SELECT project_id
                        FROM projects
                        WHERE project_name = ?
                        """
                    ),
                    (project_name,),
                ).fetchone()

                if not project:

                    print(
                        f"❌ Project '{project_name}' not found"
                    )

                    return False, None

                project_id = project[0]

                # -------------------------------------------------------------
                # Check duplicate Run ID
                # -------------------------------------------------------------

                is_duplicate = (
                    conn.execute(
                        _prepare_sql(
                            """
                            SELECT 1
                            FROM pretest_changes
                            WHERE project_id = ?
                              AND run_id = ?
                            LIMIT 1
                            """
                        ),
                        (
                            project_id,
                            run_id,
                        ),
                    ).fetchone()
                    is not None
                )

                # -------------------------------------------------------------
                # Insert record
                # -------------------------------------------------------------

                conn.execute(
                    _prepare_sql(
                        """
                        INSERT INTO pretest_changes (
                            project_id,
                            run_id,
                            tier,
                            changes,
                            change_date
                        )
                        VALUES (?, ?, ?, ?, ?)
                        """
                    ),
                    (
                        project_id,
                        run_id,
                        tier,
                        changes,
                        change_date,
                    ),
                )

                conn.commit()

                return True, is_duplicate

            except Exception as exc:

                conn.rollback()

                print(
                    f"❌ Database error adding pretest change: {exc}"
                )

                return False, None

    except Exception as exc:

        print(
            f"❌ Unexpected error in add_pretest_change: {exc}"
        )

        return False, None


def update_pretest_change(
    project_name,
    run_id,
    tier,
    changes,
    change_date,
):
    """
    Update an existing pretest change identified by project and Run ID.
    """

    try:

        if not all(
            [
                project_name,
                run_id,
                tier,
                changes,
                change_date,
            ]
        ):

            print(
                "❌ All fields are required for updating pretest change"
            )

            return False

        project_name = str(project_name).strip()
        run_id = str(run_id).strip()
        tier = str(tier).strip()
        changes = str(changes).strip()
        change_date = str(change_date).strip()

        with _connection() as conn:

            try:

                cursor = conn.execute(
                    _prepare_sql(
                        """
                        UPDATE pretest_changes
                        SET
                            tier = ?,
                            changes = ?,
                            change_date = ?
                        WHERE project_id = (
                            SELECT project_id
                            FROM projects
                            WHERE project_name = ?
                        )
                        AND run_id = ?
                        """
                    ),
                    (
                        tier,
                        changes,
                        change_date,
                        project_name,
                        run_id,
                    ),
                )

                conn.commit()

                return cursor.rowcount > 0

            except Exception as exc:

                conn.rollback()

                print(
                    f"❌ Database error updating pretest change: {exc}"
                )

                return False

    except Exception as exc:

        print(
            f"❌ Unexpected error in update_pretest_change: {exc}"
        )

        return False


# =============================================================================
# DATE HELPERS
# =============================================================================

def _parse_change_date(date_value):
    """
    Return a comparable date value for pretest-change records.
    """

    if date_value is None:
        return datetime.min.date()

    date_str = str(date_value).strip()

    if not date_str:
        return datetime.min.date()

    formats = (
        "%Y-%m-%d",
        "%Y-%m-%d %H:%M:%S",
        "%d-%m-%Y",
        "%d-%m-%Y %H:%M:%S",
    )

    for fmt in formats:

        try:
            return datetime.strptime(
                date_str,
                fmt,
            ).date()

        except ValueError:
            continue

    try:

        return datetime.fromisoformat(
            date_str
        ).date()

    except ValueError:

        return datetime.min.date()


# =============================================================================
# READ PRETEST CHANGES
# =============================================================================

def get_pretest_changes(project_name):
    """
    Get all pretest changes for a project,
    sorted newest first.
    """

    return get_pretest_changes_filtered(
        project_name
    )


def get_pretest_changes_filtered(
    project_name,
    run_id=None,
    tier=None,
    start_date=None,
    end_date=None,
):
    """
    Get pretest changes for a project filtered by:

        - Run ID
        - Tier
        - Start date
        - End date

    Results are sorted newest date first.
    """

    try:

        if not project_name:
            return []

        query = """
            SELECT
                run_id,
                tier,
                changes,
                change_date
            FROM pretest_changes
            WHERE project_id = (
                SELECT project_id
                FROM projects
                WHERE project_name = ?
            )
        """

        params = [
            project_name
        ]

        # ---------------------------------------------------------------------
        # Run ID filter
        # ---------------------------------------------------------------------

        if run_id:

            query += """
                AND run_id LIKE ?
            """

            params.append(
                f"%{str(run_id).strip()}%"
            )

        # ---------------------------------------------------------------------
        # Tier filter
        # ---------------------------------------------------------------------

        if tier:

            query += """
                AND tier LIKE ?
            """

            params.append(
                f"%{str(tier).strip()}%"
            )

        # ---------------------------------------------------------------------
        # Start date
        # ---------------------------------------------------------------------

        if start_date:

            query += """
                AND change_date >= ?
            """

            params.append(
                str(start_date)
            )

        # ---------------------------------------------------------------------
        # End date
        # ---------------------------------------------------------------------

        if end_date:

            query += """
                AND change_date <= ?
            """

            params.append(
                str(end_date)
            )

        # ---------------------------------------------------------------------
        # IMPORTANT:
        #
        # Do NOT use:
        #
        #     ORDER BY date(change_date)
        #
        # because that is SQLite-specific.
        #
        # change_date is already DATE, so direct ordering works in both
        # PostgreSQL and SQLite.
        # ---------------------------------------------------------------------

        query += """
            ORDER BY
                change_date DESC,
                created_timestamp DESC
        """

        with _connection() as conn:

            cursor = conn.execute(
                _prepare_sql(query),
                tuple(params),
            )

            return cursor.fetchall()

    except Exception as exc:

        print(
            f"❌ Error retrieving pretest changes: {exc}"
        )

        return []


# =============================================================================
# DATAFRAME VERSION
# =============================================================================

def get_pretest_changes_as_dataframe(project_name):
    """
    Get pretest changes as a pandas DataFrame.
    """

    import pandas as pd

    changes = get_pretest_changes(
        project_name
    )

    if not changes:

        return pd.DataFrame(
            columns=[
                "Sr. No.",
                "Run ID",
                "Tier",
                "Changes Done",
                "Date",
            ]
        )

    data = []

    for idx, (
        run_id,
        tier,
        changes_text,
        change_date,
    ) in enumerate(
        changes,
        1,
    ):

        data.append(
            {
                "Sr. No.": idx,
                "Run ID": run_id,
                "Tier": tier,
                "Changes Done": changes_text,
                "Date": change_date,
            }
        )

    return pd.DataFrame(data)


# =============================================================================
# DELETE PRETEST CHANGE
# =============================================================================

def delete_pretest_change(
    project_name,
    run_id,
):
    """
    Delete a pretest change by project and Run ID.

    If duplicate Run IDs exist within the same project,
    all matching records are deleted, preserving the behavior
    of the original application.
    """

    try:

        if not project_name or not run_id:
            return False

        with _connection() as conn:

            try:

                cursor = conn.execute(
                    _prepare_sql(
                        """
                        DELETE FROM pretest_changes
                        WHERE project_id = (
                            SELECT project_id
                            FROM projects
                            WHERE project_name = ?
                        )
                        AND run_id = ?
                        """
                    ),
                    (
                        project_name,
                        run_id,
                    ),
                )

                conn.commit()

                return cursor.rowcount > 0

            except Exception as exc:

                conn.rollback()

                print(
                    f"❌ Database error deleting pretest change: {exc}"
                )

                return False

    except Exception as exc:

        print(
            f"❌ Unexpected error in delete_pretest_change: {exc}"
        )

        return False


# =============================================================================
# DELETE PROJECT
# =============================================================================

def delete_project(project_name):
    """
    Delete a project and all associated pretest changes.
    """

    try:

        if not project_name:
            return False

        with _connection() as conn:

            try:

                # -------------------------------------------------------------
                # Find project
                # -------------------------------------------------------------

                project = conn.execute(
                    _prepare_sql(
                        """
                        SELECT project_id
                        FROM projects
                        WHERE project_name = ?
                        """
                    ),
                    (project_name,),
                ).fetchone()

                if not project:
                    return False

                project_id = project[0]

                # -------------------------------------------------------------
                # Delete child records explicitly.
                #
                # This keeps behavior consistent even if an existing database
                # was created without ON DELETE CASCADE.
                # -------------------------------------------------------------

                conn.execute(
                    _prepare_sql(
                        """
                        DELETE FROM pretest_changes
                        WHERE project_id = ?
                        """
                    ),
                    (project_id,),
                )

                # -------------------------------------------------------------
                # Delete project
                # -------------------------------------------------------------

                cursor = conn.execute(
                    _prepare_sql(
                        """
                        DELETE FROM projects
                        WHERE project_id = ?
                        """
                    ),
                    (project_id,),
                )

                conn.commit()

                return cursor.rowcount > 0

            except Exception as exc:

                conn.rollback()

                print(
                    f"❌ Database error deleting project: {exc}"
                )

                return False

    except Exception as exc:

        print(
            f"❌ Unexpected error in delete_project: {exc}"
        )

        return False
